### ISSUE TITLE
Worked a few times, now won't start.

### ISSUE THREAD

**Issue by GameKyuubi** [napcs/node-livereload#102]
## What version are you using? (Don't say latest. Be specific.)
v0.6.2
## Expected result
    livereload

Should cause the livereload server to start.  Instead it crashes.
## Actual result
```
Starting LiveReload v0.6.2 for /home/user on port 35729.
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: watch /home/user/.Private/ECRYPTFS_FNEK_ENCRYPTED.FWaOz.OTJM0oEUQMv3d-Se5ImJRkr54ve.mCWNFrbJ4ieb1n2K.4SeKwfU--/ECRYPTFS_FNEK_ENCRYPTED.FWaOz.OTJM0oEUQMv3d-Se5ImJRkr54ve.mCzJFC7-7knkr372Wk0Cjd9---/ECRYPTFS_FNEK_ENCRYPTED.FWaOz.OTJM0oEUQMv3d-Se5ImJRkr54ve.mCas9WABTNKXIHi9RlzhkSVU--/ECRYPTFS_FNEK_ENCRYPTED.FWaOz.OTJM0oEUQMv3d-Se5ImJRkr54ve.mCOq2Y17lKd.l9P-8arVsOuU-- ENOSPC
    at exports._errnoException (util.js:1014:11)
    at FSWatcher.start (fs.js:1384:19)
    at Object.fs.watch (fs.js:1410:11)
    at createFsWatchInstance (/home/user/.npm-global/lib/node_modules/livereload/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/user/.npm-global/lib/node_modules/livereload/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/user/.npm-global/lib/node_modules/livereload/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/user/.npm-global/lib/node_modules/livereload/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/user/.npm-global/lib/node_modules/livereload/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:153:5)

```
## Steps to reproduce issue
Not sure, it seemed to work fine until I started it in the background with `livereload &` and then killed it in `htop` .  I could have sworn it worked one or two more times after that but I can't be sure.  A reboot does not fix the issue, neither does reinstalling the package.
## Why is this important?
Can't use it if I can't run it!

**Comment by napcs** [comment]
Closing due to lack of activity.

**Comment by francoisromain** [comment]
I had a similar issue. Reseting npm solved it: 
`rm -rf node_modules && rm package-lock.json && npm cache clear --force`
