### ISSUE TITLE
Windows 8.1: build error MSB6006 (CL.exe exit code 5)

### ISSUE THREAD

**Issue by maiermic** [napcs/node-livereload#65]
I get a build error during install of livereload on my Windows 8.1 PC:
```
USERNAME@MYPC C:\
$ npm install -g livereload
npm WARN install Couldn't install optional dependency: Unsupported
C:\nvm\nodejs\livereload -> C:\nvm\nodejs\node_modules\livereload\bin\livereload.js

> bufferutil@1.2.1 install C:\nvm\nodejs\node_modules\livereload\node_modules\bufferutil
> node-gyp rebuild


USERNAME@MYPC C:\nvm\nodejs\node_modules\livereload\node_modules\bufferutil
$ if not defined npm_config_node_gyp (node "C:\nvm\nvm-windows\v5.4.0\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
  TRACKER : Fehler TRK0005: Fehler beim Suchen von "CL.exe". Das System kann die angegebene Datei nicht finden.


C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(356,5): error MSB6006: "CL.exe" wurde mit dem Code 5 beendet. [C:\nvm\nodejs\node_modules\livereload\node_modules\bufferutil\build\bufferutil.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\nvm\nvm-windows\v5.4.0\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\nvm\\nodejs\\node.exe" "C:\\nvm\\nvm-windows\\v5.4.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\nvm\nodejs\node_modules\livereload\node_modules\bufferutil
gyp ERR! node -v v5.4.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:bufferutil@1.2.1 bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN install:bufferutil@1.2.1 Exit status 1

> utf-8-validate@1.2.1 install C:\nvm\nodejs\node_modules\livereload\node_modules\utf-8-validate
> node-gyp rebuild


USERNAME@MYPC C:\nvm\nodejs\node_modules\livereload\node_modules\utf-8-validate
$ if not defined npm_config_node_gyp (node "C:\nvm\nvm-windows\v5.4.0\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
  TRACKER : Fehler TRK0005: Fehler beim Suchen von "CL.exe". Das System kann die angegebene Datei nicht finden.


C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(356,5): error MSB6006: "CL.exe" wurde mit dem Code 5 beendet. [C:\nvm\nodejs\node_modules\livereload\node_modules\utf-8-validate\build\validation.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\nvm\nvm-windows\v5.4.0\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\nvm\\nodejs\\node.exe" "C:\\nvm\\nvm-windows\\v5.4.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\nvm\nodejs\node_modules\livereload\node_modules\utf-8-validate
gyp ERR! node -v v5.4.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:utf-8-validate@1.2.1 utf-8-validate@1.2.1 install: `node-gyp rebuild`
npm WARN install:utf-8-validate@1.2.1 Exit status 1
C:\nvm\nodejs
└─┬ livereload@0.4.1
  ├─┬ chokidar@1.4.3
  │ ├─┬ anymatch@1.3.0
  │ │ ├── arrify@1.0.1
  │ │ └─┬ micromatch@2.3.7
  │ │   ├─┬ arr-diff@2.0.0
  │ │   │ └── arr-flatten@1.0.1
  │ │   ├── array-unique@0.2.1
  │ │   ├─┬ braces@1.8.3
  │ │   │ ├─┬ expand-range@1.8.1
  │ │   │ │ └─┬ fill-range@2.2.3
  │ │   │ │   ├── is-number@2.1.0
  │ │   │ │   ├── isobject@2.0.0
  │ │   │ │   ├── randomatic@1.1.5
  │ │   │ │   └── repeat-string@1.5.4
  │ │   │ ├── preserve@0.2.0
  │ │   │ └── repeat-element@1.1.2
  │ │   ├─┬ expand-brackets@0.1.5
  │ │   │ └── is-posix-bracket@0.1.1
  │ │   ├── extglob@0.3.2
  │ │   ├── filename-regex@2.0.0
  │ │   ├─┬ kind-of@3.0.2
  │ │   │ └── is-buffer@1.1.3
  │ │   ├── normalize-path@2.0.1
  │ │   ├─┬ object.omit@2.0.0
  │ │   │ ├─┬ for-own@0.1.4
  │ │   │ │ └── for-in@0.1.5
  │ │   │ └── is-extendable@0.1.1
  │ │   ├─┬ parse-glob@3.0.4
  │ │   │ ├── glob-base@0.3.0
  │ │   │ └── is-dotfile@1.0.2
  │ │   └─┬ regex-cache@0.4.3
  │ │     ├── is-equal-shallow@0.1.3
  │ │     └── is-primitive@2.0.0
  │ ├── async-each@1.0.0
  │ ├── glob-parent@2.0.0
  │ ├── inherits@2.0.1
  │ ├─┬ is-binary-path@1.0.1
  │ │ └── binary-extensions@1.4.0
  │ ├─┬ is-glob@2.0.1
  │ │ └── is-extglob@1.0.0
  │ ├── path-is-absolute@1.0.0
  │ └─┬ readdirp@2.0.0
  │   ├── graceful-fs@4.1.3
  │   ├─┬ minimatch@2.0.10
  │   │ └─┬ brace-expansion@1.1.3
  │   │   ├── balanced-match@0.3.0
  │   │   └── concat-map@0.0.1
  │   └─┬ readable-stream@2.1.0
  │     ├── core-util-is@1.0.2
  │     ├─┬ inline-process-browser@2.0.1
  │     │ ├─┬ falafel@1.2.0
  │     │ │ ├── acorn@1.2.2
  │     │ │ ├── foreach@2.0.5
  │     │ │ ├── isarray@0.0.1
  │     │ │ └── object-keys@1.0.9
  │     │ └─┬ through2@0.6.5
  │     │   ├── readable-stream@1.0.34
  │     │   └── xtend@4.0.1
  │     ├── isarray@1.0.0
  │     ├── process-nextick-args@1.0.6
  │     ├── string_decoder@0.10.31
  │     ├─┬ unreachable-branch-transform@0.5.1
  │     │ ├── esmangle-evaluator@1.0.0
  │     │ └─┬ recast@0.11.5
  │     │   ├── ast-types@0.8.16
  │     │   ├── esprima@2.7.2
  │     │   ├── private@0.1.6
  │     │   └── source-map@0.5.3
  │     └── util-deprecate@1.0.2
  ├── opts@1.2.2
  └─┬ ws@0.8.1
    ├── options@0.0.6
    └── ultron@1.0.2
```

I can run it
```
USERNAME@MYPC C:\tmp
$ livereload .\
Starting LiveReload v0.4.1 for C:\tmp on port 35729.
```
but it does not reload any files in my browser. However, it works if I use the regular GUI-Version (I installed Windows version [LiveReload 0.9.2 Alpha](http://download.livereload.com/windows/LiveReloadSetup.exe)) instead. Nevertheless, I would prefer to use livereload from the commandline.

**Comment by napcs** [comment]
It's an issue with your machine and Visual Studio and one of the dependencies of this program (bufferutil). 

```
error MSB6006: "CL.exe" wurde mit dem Code 5 beendet..."
```
See <http://stackoverflow.com/questions/32339480/can-not-install-ember-cli-with-npm> for a similar issue and suggestions.  

Closing this as it doesn't seem like a bug directly related to Livereload. But feel free to reopen if you get sent back here by another dev.

**Comment by maiermic** [comment]
Thanks. `npm config set msvs_version 2013 --global` solved that problem for me.
